case:
  - TestAccount-test_check_email
  - TestAccount-test_send_sms_code
  - TestAccount-test_sms_register
  - TestAccount-test_register
 #  - TestAccount-test_reset_password
#  - TestAccount-test_change_password #导致登录失效
#  - TestAccount-test_put_reset_password #导致登录失效
 - TestAccount-test_login
 - TestAccount-test_version_tips
 - TestAccount-test_ws_url
 - TestAccount-test_user_teams
 - TestAccount-test_get_user_settings
 - TestAccount-test_user_profile
 - TestAccount-test_user_detail
 - TestAccount-test_put_userinfo
 - TestAccount-test_user_pop_up
 - TestAccount-test_current_user_in_list
 - TestAccount-test_wechat
 - TestAccount-test_lark_lark
 - TestTeam-test_creat_team
 - TestOrder-test_business_package
 - TestOrder-test_create_order
 - TestOrder-test_cancel_order
 - TestOrder-test_contract
 - TestOrder-test_company_info
 - TestOrder-test_invoice
 - TestOrder-test_invoiceInfo
 - TestOrder-test_team_service
 - TestOrder-test_put_team_service
 - TestOrder-test_expire_notice
 - TestOrder-test_order_list
 - TestFolder-test_create_folder
 - TestFolder-test_rename_folder
 - TestFolder-test_get_folder
 - TestTeam-test_get_team
 - TestTeam-test_put_team
 - TestTeam-test_create_department
 - TestTeam-test_del_department
 - TestTeam-test_serializer
 - TestTeam-test_short_url
 - TestTeam-test_put_invite_member
 - TestTeam-test_put_invite_no_trace
 - TestTeam-test_remove_member
 - TestTeam-test_search_member
 - TestProject-test_create_project
 - TestProject-test_share_project
 - TestProject-test_project_add_member
 - TestProject-test_user_pic_status
 - TestTeam-test_users_to_projects
 - TestTeam-test_recently_used_project
 - TestProject-test_project_usernames
 - TestProject-test_project_rm_member
 - TestTeam-test_update_member
 - TestTeam-test_update_projects
 - TestProject-test_change_project_type
 - TestProject-test_change_project_name
 - TestProject-test_get_project_info
 - TestProject-test_multiple_projects
 - TestProject-test_move_project
 - TestProject-test_move_project_folder
 - TestFolder-test_folder_projects
 #  - TestImage-test_upload_files
 - TestImage-test_upload_image
 - TestImage-test_get_image
 - TestImage-test_image_type
 - TestImage-test_copyimage
 - TestImage-test_get_compressed
 - TestImage-test_image_home
 - TestImage-test_get_image_home
 - TestImage-test_prototype
 - TestImage-test_get_prototype
 - TestImage-test_sector
 - TestImage-test_rename_sector
 - TestImage-test_get_project_sectors
 - TestImage-test_change_sector
 - TestImage-test_sector_sort
 - TestImage-test_sector_image_sort
 - TestImage-test_del_sector
 - TestImage-test_card
 - TestImage-test_upload_file
 - TestImage-test_search_image
 - TestImage-test_update_version
 - TestImage-test_image_contrast
 - TestImage-test_link
 - TestImage-test_connection_explain
 - TestImage-test_del_link
 - TestImage-test_comment
 - TestImage-test_change_comment_status
 - TestImage-test_del_comment
 - TestImage-test_del_file
 - TestImage-test_del_image
 - TestImage-test_bookmark
 - TestImage-test_get_bookmark
 - TestImage-test_put_bookmark
 - TestImage-test_del_bookmark
 - TestSearch-test_search
 - TestNotify-test_notify_team
 - TestNotify-test_put_notify_team
 - TestNotify-test_notify_project
 - TestNotify-test_put_notify_project
 - TestFolder-test_one_folder_projects
 - TestTeam-test_users_in_department
 - TestTeam-test_user_folder_project
 - TestTeam-test_user_projects_cnt
 - TestTeam-test_team_detail
 - TestPlugin-test_store_token
 - TestPlugin-test_get_login_token
 - TestPlugin-test_plugin_user_teams
 - TestPlugin-test_plugin_err_status
 - TestProject-test_del_project
 - TestFolder-test_del_folder
 - TestTeam-test_dsm_project
 - TestTeam-test_del_team
 - TestTeam-test_transfer_team
 - TestProject-test_quit_project
 - TestTeam-test_quit_team
 - TestAccount-test_logout
 - TestDown-test_app_version
##  - TestDown-test_down_file# 下载文件用例，注释不执行
#
